spring:
  application:
    name: analyzer-service

  datasource:
    url: jdbc:postgresql://localhost:5431/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  mongodb:
    host: localhost
    port: 27017
    database: documents
    username: admin
    password: root
    authentication-database: admin
    auto-index-creation: true

  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat

server:
  port: 8081